# world_size: int
# data_size: int (KB)
# master_host: str
# master_port: int
# ctrl_host: str
# ctrl_port: int
# iteration_num: int
# start_rank: int
rank_size_this_machine: 4
world_size: 4
data_size: 1024
master_host: "192.168.1.26"
master_port: 49155
ctrl_host: "192.168.1.26"
ctrl_port: 49156
iteration_num: 2
start_rank: 0