# world_size: int
# data_size: int (KB)
# master_host: str
# master_port: int
# ctrl_host: str
# ctrl_port: int
# iteration_num: int
rank_size_this_machine: 20
world_size: 20
data_size: 102400
master_host: "127.0.0.1"
master_port: 49155
ctrl_host: "127.0.0.1"
ctrl_port: 49156
iteration_num: 2
